[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[[build.steps]]
name = "Install system dependencies"
command = "apt-get update && apt-get install -y libpq-dev build-essential"
